teachingDevPath: ~/repos/teaching-dev
expectedBranch: feature/plugin-setup
controlledElements:
  - src: docusaurus.config.ts
    dst: docusaurus.config.ts
  - src: src/
    dst: src
    ignore: src/theme
  - src: tsconfig.json
    dst: tsconfig.json
  - src: vitest.config.ts
    dst: vitest.config.ts
  - src: docs/tdev/
    dst: docs/material/Components-Gallery/99-Teaching-Dev
  - src: static/bry-libs/
    dst: static/bry-libs
watch:
  - .babel.config.js
  - package.json
  - .env.example
  - src/theme/**
