---
default:
  markers:
    draft: 0
  mappings:
    - section: index.mdx
      material: structure/script-landing-pages/drafts.mdx
    - section: BYOD-Basics
      material: BYOD-Basics
    - section: Components-Gallery
      material: Components-Gallery
    - section: Datenbanken
      material: Datenbanken
    - section: Erste-Hilfe
      material: Erste-Hilfe
    - section: HTML-CSS
      material: HTML-CSS
    - section: Information-Daten
      material: Information-Daten
    - section: IT-Basics-Legacy
      material: IT-Basics-Legacy
    - section: Kryptologie
      material: Kryptologie
    - section: Microbit
      material: Microbit
    - section: Netzwerke
      material: Netzwerke
    - section: Online-Recherche
      material: Online-Recherche
    - section: Programmieren
      material: Programmieren
    - section: Programmieren-1
      material: Programmieren-1
    - section: Pygame
      material: Pygame
    - section: structure
      material: structure
    - section: Word
      material: Word
    - section: Word-Legacy
      material: Word-Legacy