---
default:
  markers:
    draft: 0
  mappings:
    - section: index.mdx
      material: structure/script-landing-pages/drafts.mdx
    - section: 01-Components
      material: Components-Gallery
    - section: 02-Game-Projekt/01-Pygame/index.mdx
      material: Pygame/index.mdx
    - section: 02-Game-Projekt/01-Pygame/img
      material: Pygame/img
    - section: 02-Game-Projekt/01-Pygame/01-Pygame-Einrichten.mdx
      material: Pygame/Misc/Pygame-Einrichten.mdx
    - section: 02-Game-Projekt/01-Pygame/img
      material: Pygame/Misc/img
    - section: 02-Game-Projekt/01-Pygame/02-Breakout-Tutorial
      material: Pygame/Breakout-Basics
    - section: 02-Game-Projekt/02-Text-Adventure
      material: Programmieren/Text-Adventure-GYM2
    - section: 02-Game-Projekt/99-Advanced-Python
      material: Programmieren/Advanced-Python
