---
gym1:
  markers:
    gbsl.gym1: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-gym1.mdx
    - section: 01-IT-Basics
      material: IT-Basics
    - section: 02-Textverarbeitung-und-Style/_category_.json
      material: structure/categories/textverarbeitung-und-style.json
    - section: 02-Textverarbeitung-und-Style/Word
      material: Word
gym2:
  markers:
    gbsl.gym2: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-gym2.mdx
    - section: 01-Kryptologie
      material: Kryptologie
      ignore:
        - 98-Spendenaufruf-Geburtstagsfeier
        - 99-secureLink.mdx
fms1:
  markers:
    gbsl.fms1: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-fms1.mdx
