---
gym1:
  markers:
    gbsl.gym1: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-gym1.mdx
    - section: 01-IT-Basics
      material: IT-Basics
    - section: 02-Textverarbeitung-und-Style/_category_.json
      material: structure/categories/textverarbeitung-und-style.json
    - section: 02-Textverarbeitung-und-Style/01-Word
      material: Word
    - section: 02-Textverarbeitung-und-Style/02-Online-Recherche
      material: Online-Recherche
    - section: 02-Textverarbeitung-und-Style/03-HTML-CSS
      material: HTML-CSS
    - section: 02-Textverarbeitung-und-Style/03-HTML-CSS/99-Thonny
      material: Programmieren/Thonny
gym2:
  markers:
    gbsl.gym2: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-gym2.mdx
    - section: 01-Kryptologie
      material: Kryptologie
      ignore:
        - 99-secureLink.mdx
    - section: 07-Game-Development/_category_.json
      material: structure/categories/game-development.json
    - section: 07-Game-Development/01-Pygame/index.mdx
      material: Pygame/index.mdx
    - section: 07-Game-Development/01-Pygame/img
      material: Pygame/img
    - section: 07-Game-Development/01-Pygame/img
      material: Pygame/Misc/img
    - section: 07-Game-Development/01-Pygame/01-Pygame-Einrichten.mdx
      material: Pygame/Misc/Pygame-Einrichten.mdx
    - section: 07-Game-Development/01-Pygame/02-Breakout-Tutorial
      material: Pygame/Breakout-Basics
    - section: 07-Game-Development/01-Pygame/03-Breakout-Inspiration.mdx
      material: Pygame/Breakout-Inspiration.mdx
    - section: 07-Game-Development/01-Pygame/99-Advanced-Python
      material: Programmieren/Advanced-Python
    - section: 07-Game-Development/02-Text-Adventure
      material: Programmieren/Text-Adventure-GYM2
    - section: 07-Game-Development/02-Text-Adventure/99-Advanced-Python
      material: Programmieren/Advanced-Python
fms1:
  markers:
    gbsl.fms1: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/gbsl-fms1.mdx
    - section: 01-Codierung
      material: Codierung
    - section: 01-Programmieren/01-Text-Adventure
      material: Programmieren/Text-Adventure
