---
26d:
  markers:
    lerb.26d: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/lerbermatt-gym2.mdx
    - section: 01-Netzwerke/img
      material: Netzwerke/img
    - section: 01-Netzwerke/index.mdx
      material: Netzwerke/index.mdx
    - section: 01-Netzwerke/01-Anfaenge-des-Web.mdx
      material: Netzwerke/04-Anfaenge-des-Web.mdx
    - section: 01-Netzwerke/01-Aufgaben-Routing-im-Alltag.mdx
      material: Netzwerke/50-Aufgaben-Routing-im-Alltag.mdx
    - section: 01-Netzwerke/02-Routing-im-Internet.mdx
      material: Netzwerke/51-Routing-im-Internet.mdx
    - section: 01-Netzwerke/03-DNS.mdx
      material: Netzwerke/60-DNS.mdx
    - section: 02-Thonny
      material: Programmieren/Thonny
    - section: 03-Pygame/index.mdx
      material: Pygame/index.mdx
    - section: 03-Pygame/img
      material: Pygame/img
    - section: 03-Pygame/01-Pygame-Einrichten.mdx
      material: Pygame/Misc/Pygame-Einrichten.mdx
    - section: 03-Pygame/img
      material: Pygame/Misc/img
    - section: 03-Pygame/02-Breakout-Tutorial
      material: Pygame/Breakout-Basics
    - section: 03-Pygame/03-Breakout-Inspiration.mdx
      material: Pygame/Breakout-Inspiration.mdx
    - section: 03-Pygame/99-Advanced-Python
      material: Programmieren/Advanced-Python
    - section: 04-Kryptologie
      material: Kryptologie
      ignore:
        - 08-Hashing
        - 09-Signatur
        - 99-secureLink.mdx
27k:
  markers:
    lerb.27k: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/lerbermatt-gym1.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/img
      material: Programmieren/Python-Cheatsheets/img
    - section: 01-Programmieren/01-Python-Cheatsheets/index.mdx
      material: Programmieren/Python-Cheatsheets/index.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/01-Schleifen.mdx
      material: Programmieren/Python-Cheatsheets/01-Schleifen.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/02-Variablen-und-Datentypen.mdx
      material: Programmieren/Python-Cheatsheets/02-Variablen-und-Datentypen.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/05-Input-Output.mdx
      material: Programmieren/Python-Cheatsheets/05-Input-Output.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/06-Verzweigungen.mdx
      material: Programmieren/Python-Cheatsheets/06-Verzweigungen.mdx
    - section: 01-Programmieren/01-Python-Cheatsheets/07-Vergleichsoperatoren-und-Logische-Operatoren.mdx
      material: Programmieren/Python-Cheatsheets/07-Vergleichsoperatoren-und-Logische-Operatoren.mdx
    - section: 01-Programmieren/02-Text-Adventure
      material: Programmieren/Text-Adventure
