---
26d:
  markers:
    lerb.26d: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/lerbermatt-gym2.mdx
    - section: 01-Netzwerke/img
      material: Netzwerke/img
    - section: 01-Netzwerke/index.mdx
      material: Netzwerke/index.mdx
    - section: 01-Netzwerke/01-Anfaenge-des-Web.mdx
      material: Netzwerke/04-Anfaenge-des-Web.mdx
27k:
  markers:
    lerb.27k: 0
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/lerbermatt-gym1.mdx
