---
gymnasium/informatik:
  markers:
    gym: 1
  mappings:
    - section: "/index.md"
      material: "/ScriptLandingPages/teach.gym.mdx"
    - section: 01-Netzwerke
      material: Netzwerke
    - section: 02-Kryptologie
      material: Kryptologie
    - section: 03-Microbit/img
      material: Microbit/img
    - section: 03-Microbit/index.mdx
      material: Microbit/Der-Microbit.gym.mdx
    - section: 03-Microbit/01-Projektideen
      material: Microbit/Projektideen-Python
sekundarstufe/medien-und-informatik:
  markers:
    sek: 1
  mappings:
    - section: "/index.md"
      material: "/ScriptLandingPages/teach.sek.mdx"
    - section: Programmieren-Microbit/img
      material: Microbit/img
    - section: Programmieren-Microbit/index.mdx
      material: Microbit/Der-Microbit.prim-sek.mdx
    - section: Programmieren-Microbit/01-Projektideen-Python
      material: Microbit/Projektideen-Python
primarstufe/medien-und-informatik:
  markers:
    prim: 1
  mappings:
    - section: "/index.md"
      material: "/ScriptLandingPages/teach.prim.mdx"
    - section: Programmieren-Microbit/img
      material: Microbit/img
    - section: Programmieren-Microbit/index.mdx
      material: Microbit/Der-Microbit.prim-sek.mdx
creative-corner:
  markers:
    cc: 1
  mappings:
    - section: index.md
      material: "/ScriptLandingPages/creative-corner.mdx"
    - section: "/01-Komponentengalerie"
      material: "/Components-Gallery"
