---
gymnasium/informatik:
  markers:
    gym: 1
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/teach.gym.mdx
    - section: 01-IT-Basics
      material: IT-Basics-Legacy
    - section: 02-Programmieren/01-Thonny
      material: Programmieren/Thonny
    - section: 02-Programmieren/99-Advanced-Python
      material: Programmieren/Advanced-Python
    - section: 03-Textverarbeitung-und-Style/_category_.json
      material: structure/categories/textverarbeitung-und-style.json
    - section: 03-Textverarbeitung-und-Style/01-Word
      material: Word
    - section: 03-Textverarbeitung-und-Style/02-Online-Recherche
      material: Online-Recherche
    - section: 03-Textverarbeitung-und-Style/03-HTML-CSS
      material: HTML-CSS
    - section: 04-Information-Daten
      material: Information-Daten
    - section: 05-Netzwerke
      material: Netzwerke
    - section: 06-Kryptologie
      material: Kryptologie
    - section: 07-Game-Development/_category_.json
      material: structure/categories/game-development.json
    - section: 07-Game-Development/01-Pygame/index.mdx
      material: Pygame/index.mdx
    - section: 07-Game-Development/01-Pygame/img
      material: Pygame/img
    - section: 07-Game-Development/01-Pygame/img
      material: Pygame/Misc/img
    - section: 07-Game-Development/01-Pygame/01-Pygame-Einrichten.mdx
      material: Pygame/Misc/Pygame-Einrichten.mdx
    - section: 07-Game-Development/01-Pygame/02-Breakout-Tutorial
      material: Pygame/Breakout-Basics
    - section: 07-Game-Development/01-Pygame/03-Breakout-Inspiration.mdx
      material: Pygame/Breakout-Inspiration.mdx
    - section: 07-Game-Development/01-Pygame/99-Advanced-Python
      material: Programmieren/Advanced-Python
    - section: 07-Game-Development/02-Text-Adventure
      material: Programmieren/Text-Adventure-GYM2
    - section: 08-Microbit/img
      material: Microbit/img
    - section: 08-Microbit/index.mdx
      material: Microbit/Der-Microbit.gym.mdx
    - section: 08-Microbit/01-Projektideen
      material: Microbit/Projektideen-Python
sekundarstufe/medien-und-informatik:
  markers:
    sek: 1
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/teach.sek.mdx
    - section: Programmieren-Microbit/img
      material: Microbit/img
    - section: Programmieren-Microbit/index.mdx
      material: Microbit/Der-Microbit.prim-sek.mdx
    - section: Programmieren-Microbit/01-Projektideen-Python
      material: Microbit/Projektideen-Python
primarstufe/medien-und-informatik:
  markers:
    prim: 1
  mappings:
    - section: /index.md
      material: /structure/script-landing-pages/teach.prim.mdx
    - section: Programmieren-Microbit/img
      material: Microbit/img
    - section: Programmieren-Microbit/index.mdx
      material: Microbit/Der-Microbit.prim-sek.mdx
creative-corner:
  markers:
    cc: 1
  mappings:
    - section: index.md
      material: /structure/script-landing-pages/creative-corner.mdx
    - section: 01-Komponentengalerie
      material: Components-Gallery
