import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "G26c": [{type: 'autogenerated', dirName: '.'}],
  "G27i": [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
