import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "gym1": [{type: 'autogenerated', dirName: '.'}],
  "gym2": [{type: 'autogenerated', dirName: '.'}],
  "fms1": [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
