import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "26d": [{type: 'autogenerated', dirName: '.'}],
  "27k": [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
