import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {materialbibliothekSidebar} from "./materialbibliothek";
import {g26cSidebar} from "./klassen/g26c";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contentSidebar: [{type: 'autogenerated', dirName: '.'}],
  materialbibliothekSidebar: materialbibliothekSidebar,
  g26cSidebar: g26cSidebar,
};

export default sidebars;
