import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "gymnasium/informatik": [{type: 'autogenerated', dirName: '.'}],
  "sekundarstufe/medien-und-informatik": [{type: 'autogenerated', dirName: '.'}],
  "primarstufe/medien-und-informatik": [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
