/*
tutorialSidebar: [
  'intro',
  'hello',
  {
    type: 'category',
    label: 'Tutorial',
    items: ['tutorial-basics/create-a-document'],
  },
],


export type SidebarConfig = SidebarCategoriesShorthand | SidebarItemConfig[];
export type SidebarCategoriesShorthand = {
  [sidebarCategory: string]: SidebarCategoriesShorthand | SidebarItemConfig[];
};
export type SidebarItemConfig =
  | Omit<SidebarItemDoc, 'translatable'>
  | SidebarItemHtml
  | SidebarItemLink
  | SidebarItemAutogenerated
  | SidebarItemCategoryConfig
  | string
  | SidebarCategoriesShorthand;

export type SidebarItemBase = {
  className?: string;
  customProps?: {[key: string]: unknown};
};
 */

/*
export type SidebarItemDoc = SidebarItemBase & {
  type: 'doc' | 'ref';
  label?: string;
  id: string;
  translatable?: true;
};

export type SidebarItemHtml = SidebarItemBase & {
  type: 'html';
  value: string;
  defaultStyle?: boolean;
};

export type SidebarItemLink = SidebarItemBase & {
  type: 'link';
  href: string;
  label: string;
  autoAddBaseUrl?: boolean;
  description?: string;
};
 */

const basePath = 'content/material/master/DemoThema';

export const demoThemaSidebar = [
  'DemoThema/Intro',
  {
    type: 'category',
    label: 'Einführung',
    items: [
      'DemoThema/Einfuehrung/Basics',
      'DemoThema/Einfuehrung/HaeufigeFehler',
    ]
  },
  {
    type: 'category',
    label: 'Erstes Subthema',
    items: [
      'DemoThema/ErstesSubthema/Uebersicht',
      {
        type: 'category',
        label: 'Vier Aspekte',
        items: [
          'DemoThema/ErstesSubthema/VierAspekte/ErsterAspekt',
          'DemoThema/ErstesSubthema/VierAspekte/ZweiterAspekt',
          'DemoThema/ErstesSubthema/VierAspekte/DritterAspekt',
          'DemoThema/ErstesSubthema/VierAspekte/VierterAspekt',
        ]
      }
    ]
  }
];
