name: Deploy Application
run-name: ${{ github.actor }} is deploying the teaching website 🚀
on:
  push:
    branches:
      - main
      - feature/first-content
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node setup
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    # TODO: Check whether there's a yarn action to simplify this.
    # TODO: Get site from matrix param.
    - name: Yarn build
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi
        SITE=teach npm run build

    # TODO: Derive remote path from matrix param.
    - name: RSync to webhost
      uses: Burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: build/
        remote_path: ~/sites/teach.silasberger.ch/
        remote_host: ${{ secrets.WEBHOST_SSH_HOSTNAME }}
        remote_user: ${{ secrets.WEBHOST_SSH_USERNAME }}
        remote_key: ${{ secrets.WEBHOST_SSH_PRIVATE_KEY }}
