name: Deploy to GitHub Pages
run-name: Run checks and deploying to GitHub Pages 🚀

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_check:
    name: Build and run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.TW_CONFIDENTIAL_MATERIAL_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: '>=22.15.0'
          cache: yarn
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prettier format check (warning only)
        run: yarn run format:check || echo "⚠️ Prettier formatting issues detected - please fix!"
      - name: Test
        run: yarn run test:site
      - name: Building application
        run: yarn run build
        working-directory: .
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          API_URI: ${{ secrets.API_URI }}
          APP_URL: ${{ secrets.APP_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          GH_OAUTH_CLIENT_ID: ${{ secrets.GH_OAUTH_CLIENT_ID }}
          UMAMI_ID: ${{ secrets.UMAMI_ID }}
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    needs: build_and_check
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

